# Generated by Django 4.1.7 on 2023-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_created_at_accounts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='mohbaba@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
