# Generated by Django 4.1.7 on 2023-04-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(default='oreoluwa', max_length=100),
        ),
    ]
